language: csharp
mono: latest
dotnet: 2.1.302
before_build:
 - nuget restore
 - choco install opencover.portable
 - choco install codecov

script:
 - dotnet build
 - dotnet test NameSorterTester/NameSorterTester.csproj
 - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\NameSorter\bin\Debug\netcoreapp2.1\NameSorter.dll -noshadow" -filter:"+[NameSorterTester*]* -[NameSorter*]*" -output:".\MyProject_coverage.xml"
 - codecov -f "MyProject_coverage.xml
